Fix to compile in MS Visual C++
1. #include <algorithm>
   Needed to stop error C2039: 'min': is not a member of 'std'

2. #pragma warning( disable : 4290 )
   Needed to stop warning C4290: C++ exception specification ignored except to indicate a function is not __declspec(nothrow)
   See https://msdn.microsoft.com/en-us/library/sa28fef8.aspx

3. nearly_equal<double> instead of nearly_equal<float> if any of the arguments is double
   Needed to stop warning C4244: 'argument': conversion from 'const double' to 'const float', possible loss of data